name: NuGet Pack and Publish

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/README.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/README.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: NuGet/setup-nuget@v2
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}

      - name: Create package
        run: nuget pack KnowYourToolset.Templates.nuspec -NoDefaultExcludes

      - name: Publish NuGet
        run: nuget push *.nupkg -src https://api.nuget.org/v3/index.json
